// @/types/panel/survey.ts
import { User } from "@/app/api/auth";


export type SurveyStatus = "draft" | "open" | "closed" | "archived";

export interface WeightingSurvey {
  id: number;
  title: string;
  description: string;
  status: SurveyStatus;
  opened_at: string | null;
  closed_at: string | null;
  created_by: number | null;
  created_at: string;
  updated_at: string;
}

export interface WeightingAllocation {
  id?: number;
  criterion: string; // criterion slug
  points: number;
}

export interface WeightingKillerFlag {
  id?: number;
  candidate: string; // killer-candidate slug
  is_killer: boolean;
  rank: number | null; // 1..3
  other_text: string;
}

export interface WeightingResponse {
  id: number;
  survey: number;
  respondent: number;
  respondent_name: string;
  respondent_role: string;
  response_date: string | null;
  sensitivity_criterion: string;
  scenario_1_choice: string;
  scenario_2_choice: string;
  submitted_at: string | null;
  created_at: string;
  updated_at: string;
  allocations: WeightingAllocation[];
  killer_flags: WeightingKillerFlag[];
}

// Payload the page POSTs to {id}/submit/
export interface WeightingResponsePayload {
  respondent_name: string;
  respondent_role: string;
  response_date: string | null;
  sensitivity_criterion: string;
  scenario_1_choice: string;
  scenario_2_choice: string;
  allocations: WeightingAllocation[];
  killer_flags: WeightingKillerFlag[];
}

// Committee aggregation from {id}/scores/
export interface CriterionScore {
  criterion: string;
  total_points: number;
}

export interface ResponseRow {
  respondent_name: string;
  points: Record<string, number>; // criterion slug -> points
  sensitivity_criterion: string;
  scenario_1_choice: string;
  scenario_2_choice: string;
}
export interface WeightingScores {
  survey_id: number;
  respondent_count: number;
  criteria: CriterionScore[];
  responses: ResponseRow[];
  killer_criteria: Record<string, { votes: number; rank_score: number }>;
  sensitivity: Record<string, number>;
  scenario_1: Record<string, number>;
  scenario_2: Record<string, number>;
}

export type { User };

// ---------------------------------------------------------------------------
// Part A criteria (from HTA_Criteria_Weighting_Survey.xlsx). Shared enough to
// live here; killer candidates, scenarios, and TOTAL_POINTS live in the page.
// ---------------------------------------------------------------------------
export const CRITERIA: { slug: string; no: number; name: string; description: string }[] = [
  { slug: "clinical_effectiveness", no: 1, name: "Clinical Effectiveness", description: "The degree to which the technology improves health outcomes (e.g. survival, symptom relief) relative to current standard of care." },
  { slug: "safety", no: 2, name: "Safety", description: "The frequency, severity, and reversibility of adverse effects or harms associated with the technology." },
  { slug: "quality_of_evidence", no: 3, name: "Quality of Evidence", description: "The robustness, consistency, and certainty of the clinical and economic evidence submitted." },
  { slug: "burden_of_disease", no: 4, name: "Burden of Disease", description: "The severity of the condition and its impact on patients' quality of life, function, and life expectancy." },
  { slug: "incidence_prevalence", no: 5, name: "Incidence / Prevalence", description: "How common the condition is within the population, now and projected over time." },
  { slug: "population_impact", no: 6, name: "Population Impact", description: "The number of people expected to benefit from the technology if adopted." },
  { slug: "equity", no: 7, name: "Equity", description: "The technology's effect on reducing (or widening) health disparities among vulnerable or underserved groups." },
  { slug: "cost_effectiveness", no: 8, name: "Cost-Effectiveness", description: "The value for money generated by the technology relative to its cost, versus existing alternatives." },
  { slug: "budget_impact", no: 9, name: "Budget Impact", description: "The affordability of the technology and its financial impact on the overall health budget." },
  { slug: "feasibility_of_implementation", no: 10, name: "Feasibility of Implementation", description: "The health system's readiness and capacity to deliver the technology (infrastructure, workforce, logistics)." },
  { slug: "catastrophic_health_expenditure", no: 11, name: "Catastrophic Health Expenditure", description: "The degree to which the technology protects patients and households from financial hardship due to out-of-pocket costs." },
  { slug: "government_alignment", no: 12, name: "Alignment with Government Priorities", description: "The consistency of the technology with national health strategy, policy priorities, and public health goals." },
];